[tool.poetry]
name = "clogstats"
version = "0.1.0"
description = "Gather statistics from WeeChat log files"
readme = "README.md"
authors = ["Rohan Kumar <seirdy@protonmail.com>"]
homepage = "https://git.sr.ht/~seirdy/clogstats"
repository = "https://git.sr.ht/~seirdy/clogstats"
license = "AGPL-3.0-or-later"

[tool.poetry.dependencies]
python = "^3.6.1"
pandas = ">=0.25.3, <2.0.0"
dataclasses = {version = "^0.7", python = ">=3.6.1, <3.7"}

[tool.poetry.scripts]
clogstats = "clogstats.cli:main"

[tool.poetry.dev-dependencies]
black = "^19.10b0"
flake8-bandit = "^2.1.2"
flake8-bugbear = "^20.1.4"
flake8-black = "^0.2.0"
safety = "^1.9.0"
pylint = "^2.5.3"
mypy = "^0.780"
flakehell = "^0.5.0"
isort = {extras = ["pyproject"], version = "^4.3.21"}
flake8-isort = "^3.0.0"

[tool.pylint.messages_control]
disable = "C0330, C0326"

[tool.pylint.format]
max-line-length = "88"

[tool.flakehell]
format = "grouped"
max_line_length = 88
show_source = false

[tool.flakehell.plugins]
flake8-bandit = ["+*"]
flake8-black = ["+*"]
flake8-bugbear = ["+*"]
flake8-isort = ["+*"]
mccabe = ["+*"]
pycodestyle = ["+*", "-E501", "-W503"]
pyflakes = ["+*"]
pylint = ["+*", "-C0330", "-C0326"]

[tool.isort]
line_length = 88
include_trailing_comma = true
lines_after_imports = 2
lines_between_types = 1
multi_line_output = 3
use_parentheses = true

known_first_party = "clogstats"
known_third_party = [
	"pandas",
]

[tool.black]
line-length = 88
include = '\.pyi?$'
target-version = ['py36', 'py37', 'py38']

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"

